CREATE TABLE `service_quotes` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`owner_email` text NOT NULL,
	`service_name` text NOT NULL,
	`created_at` text NOT NULL,
	`start_odometer` real NOT NULL,
	`end_odometer` real NOT NULL,
	`service_km` real NOT NULL,
	`extra_km` real NOT NULL,
	`total_km` real NOT NULL,
	`fuel_price` integer NOT NULL,
	`efficiency_kpg` real NOT NULL,
	`fuel_cost` integer NOT NULL,
	`wear_per_km` integer NOT NULL,
	`wear_cost` integer NOT NULL,
	`tolls` integer NOT NULL,
	`other_costs` integer NOT NULL,
	`hours` real NOT NULL,
	`hourly_rate` integer NOT NULL,
	`time_cost` integer NOT NULL,
	`commission_pct` real NOT NULL,
	`margin_pct` real NOT NULL,
	`operating_cost` integer NOT NULL,
	`recommended_price` integer NOT NULL,
	`price_per_km` integer NOT NULL
);
